/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/decision-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_v1_decision_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_api_v1_decision_cases__case_id__evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evaluation */
        post: operations["create_evaluation_api_v1_decision_cases__case_id__evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_decision_cases__case_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/outcome-advances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Outcome Advance */
        post: operations["create_outcome_advance_api_v1_decision_cases__case_id__outcome_advances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/review-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Review Run */
        post: operations["create_review_run_api_v1_decision_cases__case_id__review_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/simulated-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Simulated Decision */
        post: operations["create_simulated_decision_api_v1_decision_cases__case_id__simulated_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_v1_decision_cases__case_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_decision_cases__case_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/fixtures/{case_id}/observable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Observable Packet */
        get: operations["get_observable_packet_api_v1_dev_fixtures__case_id__observable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Risks */
        get: operations["get_project_risks_api_v1_projects__project_id__risks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/risks/{risk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Risk Detail */
        get: operations["get_project_risk_detail_api_v1_projects__project_id__risks__risk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/situation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Situation */
        get: operations["get_project_situation_api_v1_projects__project_id__situation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Timeline */
        get: operations["get_project_timeline_api_v1_projects__project_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["stream_run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Run */
        post: operations["retry_run_api_v1_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Run Telemetry */
        get: operations["agent_run_telemetry_api_v1_telemetry_agent_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AblationResult */
        AblationResult: {
            /** Chair Used */
            chair_used: boolean;
            /** Challenger Used */
            challenger_used: boolean;
            decision: components["schemas"]["SimulatedDecision"];
            dossier: components["schemas"]["DecisionDossier"];
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Provider Attempts
             * @default 0
             */
            provider_attempts: number;
            /** Role Count */
            role_count: number;
            /**
             * Topology
             * @enum {string}
             */
            topology: "B0" | "B1" | "B2" | "B3";
        };
        /** AgentRunBudgetPlan */
        AgentRunBudgetPlan: {
            /**
             * Max Logical Calls
             * @default 9
             */
            max_logical_calls: number;
            /**
             * Max Output Tokens
             * @default 20000
             */
            max_output_tokens: number;
            /**
             * Max Provider Attempts
             * @default 12
             */
            max_provider_attempts: number;
            /** Maximum Cost Usd */
            maximum_cost_usd: number;
            /** Remaining Logical Calls */
            remaining_logical_calls: number;
            /** Remaining Output Tokens */
            remaining_output_tokens: number;
            /** Remaining Provider Attempts */
            remaining_provider_attempts: number;
            /** Reserved Logical Calls */
            reserved_logical_calls: number;
            /** Reserved Output Tokens */
            reserved_output_tokens: number;
            /** Reserved Provider Attempts */
            reserved_provider_attempts: number;
            /** Timeout Envelope Seconds */
            timeout_envelope_seconds: number;
        };
        /**
         * AgentRunStatus
         * @enum {string}
         */
        AgentRunStatus: "QUEUED" | "RUNNING" | "PARTIALLY_COMPLETED" | "COMPLETED" | "FAILED" | "CANCELLED";
        /** AgreementGroup */
        AgreementGroup: {
            recommendation: components["schemas"]["DecisionType"];
            /** Role Ids */
            role_ids: string[];
        };
        /** BlockerPropagation */
        BlockerPropagation: {
            /** Downstream Work Item Ids */
            downstream_work_item_ids: string[];
            /** Downstream Work Item Titles */
            downstream_work_item_titles: string[];
            /** Impacted Milestone Ids */
            impacted_milestone_ids: string[];
            /** Impacted Milestone Titles */
            impacted_milestone_titles: string[];
            /** Impacted Track Ids */
            impacted_track_ids: string[];
            /** Reaches Decision Deadline */
            reaches_decision_deadline: boolean;
            /** Source Work Item Id */
            source_work_item_id: string;
            /** Source Work Item Title */
            source_work_item_title: string;
        };
        /** CaseEvaluation */
        CaseEvaluation: {
            ablation: components["schemas"]["AblationResult"];
            /** Case Id */
            case_id: string;
            outcome: components["schemas"]["OutcomeSnapshot"];
            outcome_evaluation: components["schemas"]["OutcomeEvaluation"];
            /** Partition */
            partition: string;
            /** Passed */
            passed: boolean;
            process_evaluation: components["schemas"]["ProcessEvaluation"];
            /**
             * Schema Version
             * @default case-evaluation.v2
             * @enum {string}
             */
            schema_version: "case-evaluation.v1" | "case-evaluation.v2";
            /**
             * Topology
             * @enum {string}
             */
            topology: "B0" | "B1" | "B2" | "B3";
        };
        /** ChairProviderResult */
        ChairProviderResult: {
            decision: components["schemas"]["SimulatedDecision"];
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Returned Model */
            returned_model?: string | null;
            /**
             * @default {
             *       "estimated_cost_usd": 0,
             *       "input_tokens": 0,
             *       "output_tokens": 0,
             *       "provider_attempts": 1
             *     }
             */
            usage: components["schemas"]["ProviderUsage"];
        };
        /** ChallengerObjection */
        ChallengerObjection: {
            /** Claim Ids */
            claim_ids?: string[];
            /** Objection Id */
            objection_id: string;
            /** Requested Revision */
            requested_revision: string;
            /** Statement */
            statement: string;
            /** Target Role Id */
            target_role_id: string;
        };
        /** ChallengerProviderResult */
        ChallengerProviderResult: {
            challenger: components["schemas"]["ChallengerReview"];
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Returned Model */
            returned_model?: string | null;
            /**
             * @default {
             *       "estimated_cost_usd": 0,
             *       "input_tokens": 0,
             *       "output_tokens": 0,
             *       "provider_attempts": 1
             *     }
             */
            usage: components["schemas"]["ProviderUsage"];
        };
        /** ChallengerReview */
        ChallengerReview: {
            /** No Objection Reason */
            no_objection_reason?: string | null;
            /** Objections */
            objections: components["schemas"]["ChallengerObjection"][];
            /**
             * Schema Version
             * @default challenger-review.v1
             * @constant
             */
            schema_version: "challenger-review.v1";
        };
        /** DecisionActionPlan */
        DecisionActionPlan: {
            /** Action */
            action: string;
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "execute" | "collect_evidence" | "defer" | "escalate" | "reject";
            /** Due At Step */
            due_at_step: number;
            /** Escalation Target */
            escalation_target?: string | null;
            /** Evidence Required */
            evidence_required?: string[];
            /** Fallback Action */
            fallback_action: string;
            /** Owner */
            owner: string;
            /** Questions To Resolve */
            questions_to_resolve?: string[];
            /** Reopen Condition */
            reopen_condition?: string | null;
            /**
             * Schema Version
             * @default decision-action-plan.v1
             * @constant
             */
            schema_version: "decision-action-plan.v1";
            /** Trigger */
            trigger: string;
            /** Verification */
            verification: string;
        };
        /**
         * DecisionCaseStatus
         * @enum {string}
         */
        DecisionCaseStatus: "DRAFT" | "CONTEXT_BUILDING" | "OPTIONS_READY" | "DECISION_REQUIRED" | "DECIDED" | "ACTIONING" | "VERIFIED" | "CLOSED" | "REOPENED";
        /** DecisionDossier */
        DecisionDossier: {
            /** Agreement Groups */
            agreement_groups: components["schemas"]["AgreementGroup"][];
            /** Case Id */
            case_id: string;
            challenger?: components["schemas"]["ChallengerReview"] | null;
            /** Dissent */
            dissent: components["schemas"]["DissentItem"][];
            /** Original Reviews */
            original_reviews: components["schemas"]["RoleReview"][];
            /** Packet Hash */
            packet_hash: string;
            /** Revised Reviews */
            revised_reviews?: components["schemas"]["RoleReview"][];
            /**
             * Schema Version
             * @default decision-dossier.v1
             * @constant
             */
            schema_version: "decision-dossier.v1";
            /** Unresolved Uncertainties */
            unresolved_uncertainties: string[];
        };
        /** DecisionListBlocker */
        DecisionListBlocker: {
            /** Blocker Count */
            blocker_count: number;
            /** Critical Track Name */
            critical_track_name?: string | null;
            /** Critical Work Item Title */
            critical_work_item_title?: string | null;
            /** Downstream Work Item Titles */
            downstream_work_item_titles?: string[];
            /** Impacted Milestone Titles */
            impacted_milestone_titles?: string[];
            /** Summary Ko */
            summary_ko: string;
        };
        /** DecisionListDeadline */
        DecisionListDeadline: {
            /** At Step */
            at_step: number;
            /**
             * Attention
             * @enum {string}
             */
            attention: "OVERDUE" | "DUE_NOW" | "DUE_SOON" | "NORMAL";
            /** Label Ko */
            label_ko: string;
            /** Milestone Title */
            milestone_title: string;
            /** Remaining Steps */
            remaining_steps: number;
        };
        /** DecisionListItemProjection */
        DecisionListItemProjection: {
            blocker: components["schemas"]["DecisionListBlocker"];
            /** Case Id */
            case_id: string;
            case_status: components["schemas"]["DecisionCaseStatus"];
            /** Current State Ko */
            current_state_ko: string;
            deadline: components["schemas"]["DecisionListDeadline"];
            /** Decision Question */
            decision_question: string;
            /**
             * Group
             * @enum {string}
             */
            group: "ACTION_REQUIRED" | "IN_REVIEW" | "ACTION_AND_OBSERVATION" | "COMPLETED";
            /** Group Label Ko */
            group_label_ko: string;
            /**
             * Next Action
             * @default OPEN_DECISION
             * @constant
             */
            next_action: "OPEN_DECISION";
            /** Next Action Ko */
            next_action_ko: string;
            /**
             * Projection Schema Version
             * @default decision-list-item.v1
             * @constant
             */
            projection_schema_version: "decision-list-item.v1";
            /**
             * Simulated
             * @default true
             * @constant
             */
            simulated: true;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Title Ko */
            title_ko: string;
            /** Why Now Ko */
            why_now_ko: string;
        };
        /**
         * DecisionType
         * @enum {string}
         */
        DecisionType: "APPROVE" | "APPROVE_WITH_GUARDRAILS" | "RUN_REVERSIBLE_TRIAL" | "COLLECT_MINIMUM_EVIDENCE" | "DEFER_UNTIL_TRIGGER" | "REJECT" | "ESCALATE";
        /** DecisionWorkspaceProjectionV2 */
        DecisionWorkspaceProjectionV2: {
            /** Aggregate Version */
            aggregate_version: number;
            alternatives: components["schemas"]["WorkspaceAlternativesV2"];
            /** Case Id */
            case_id: string;
            controls: components["schemas"]["WorkspaceControls"];
            current_brief: components["schemas"]["WorkspaceCurrentBrief"];
            decision_posture: components["schemas"]["WorkspaceDecisionPosture"];
            deliberation: components["schemas"]["WorkspaceDeliberation"];
            details: components["schemas"]["WorkspaceDetails"];
            development_twin: components["schemas"]["WorkspaceDevelopmentTwin"];
            /** Expected Option Transitions */
            expected_option_transitions: components["schemas"]["WorkspaceExpectedOptionTransition"][];
            /** Fixture Version */
            fixture_version: number;
            /** Generated At */
            generated_at: string;
            header: components["schemas"]["WorkspaceHeaderV2"];
            observed_decision_transitions: components["schemas"]["WorkspaceObservedDecisionTransitions"];
            outcome_and_evaluation: components["schemas"]["WorkspaceOutcomeAndEvaluation"];
            /**
             * Projection Schema Version
             * @default decision-workspace.v2
             * @constant
             */
            projection_schema_version: "decision-workspace.v2";
            /** Stale */
            stale: boolean;
            time_context: components["schemas"]["WorkspaceTimeContext"];
            workflow: components["schemas"]["WorkspaceWorkflow"];
        };
        /** DevelopmentTimelineProjection */
        DevelopmentTimelineProjection: {
            /** Actions */
            actions: components["schemas"]["TimelineAction"][];
            /** Aggregate Version */
            aggregate_version: number;
            /** Blocker Propagations */
            blocker_propagations: components["schemas"]["BlockerPropagation"][];
            /** Case Id */
            case_id: string;
            /** Current Step */
            current_step: number;
            /** Events */
            events: components["schemas"]["TimelineEvent"][];
            /** Evidence */
            evidence: components["schemas"]["TimelineEvidence"][];
            /** Milestones */
            milestones: components["schemas"]["TimelineMilestone"][];
            /**
             * Projection Schema Version
             * @default development-timeline.v1
             */
            projection_schema_version: string;
            /** Reconstructed At Step */
            reconstructed_at_step: number;
            /** Work Items */
            work_items: components["schemas"]["TimelineWorkItem"][];
        };
        /** DissentItem */
        DissentItem: {
            /** Rationale */
            rationale: string;
            recommendation: components["schemas"]["DecisionType"];
            /** Role Id */
            role_id: string;
        };
        /** DossierExecution */
        DossierExecution: {
            /** Accepted Revision Results */
            accepted_revision_results?: components["schemas"]["ProviderReviewResult"][];
            /** Accepted Role Results */
            accepted_role_results?: components["schemas"]["ProviderReviewResult"][];
            chair_provider_result?: components["schemas"]["ChairProviderResult"] | null;
            challenger_provider_result?: components["schemas"]["ChallengerProviderResult"] | null;
            /** Challenger Used */
            challenger_used: boolean;
            dossier: components["schemas"]["DecisionDossier"];
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /** Failed Revisions */
            failed_revisions?: components["schemas"]["RoleFailure"][];
            /** Failed Roles */
            failed_roles?: components["schemas"]["RoleFailure"][];
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Provider Attempts
             * @default 0
             */
            provider_attempts: number;
            /** Returned Models */
            returned_models: string[];
            /** Role Count */
            role_count: number;
            /**
             * Schema Version
             * @default dossier-execution.v1
             * @constant
             */
            schema_version: "dossier-execution.v1";
            /**
             * Topology
             * @enum {string}
             */
            topology: "B1" | "B2" | "B3";
        };
        /** Evidence */
        Evidence: {
            /** Available At Step */
            available_at_step: number;
            /** Evidence Id */
            evidence_id: string;
            /** Evidence Type */
            evidence_type: string;
            /** Limitations */
            limitations?: string[];
            quantity?: components["schemas"]["Quantity"] | null;
            /** Source Ref */
            source_ref: string;
            /** Title */
            title: string;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "REQUESTED" | "LATE" | "RECEIVED";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MilestoneStatus
         * @enum {string}
         */
        MilestoneStatus: "PLANNED" | "AT_RISK" | "ACHIEVED";
        /** OutcomeAdvanceRequest */
        OutcomeAdvanceRequest: {
            /**
             * Command Schema Version
             * @default outcome-advance-command.v1
             */
            command_schema_version: string;
            decision?: components["schemas"]["SimulatedDecision"] | null;
            /** From Step */
            from_step: number;
            /** To Step */
            to_step: number;
        };
        /** OutcomeEvaluation */
        OutcomeEvaluation: {
            /** Evidence Revealed */
            evidence_revealed: boolean;
            /** Passed */
            passed: boolean;
            /** Risk Contained */
            risk_contained: boolean;
            /** Rule Executed */
            rule_executed: boolean;
        };
        /** OutcomeSnapshot */
        OutcomeSnapshot: {
            /** Advanced From Step */
            advanced_from_step: number;
            /** Case Id */
            case_id: string;
            /** Consequences */
            consequences: string[];
            /** Current Step */
            current_step: number;
            /** Decision Id */
            decision_id: string;
            /** Event Ids */
            event_ids: string[];
            /** Executed Actions */
            executed_actions: string[];
            /**
             * Guardrail State
             * @enum {string}
             */
            guardrail_state: "not_applicable" | "monitoring" | "triggered";
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Outcome Rule Version */
            outcome_rule_version: string;
            /** Revealed Evidence */
            revealed_evidence: string[];
            /** Rule Id */
            rule_id: string;
            /**
             * Schema Version
             * @default outcome-snapshot.v1
             * @constant
             */
            schema_version: "outcome-snapshot.v1";
            /** Selected Option Id */
            selected_option_id: string;
        };
        /** ProcessEvaluation */
        ProcessEvaluation: {
            /**
             * Blocker Impact Traceable
             * @default true
             */
            blocker_impact_traceable: boolean;
            /** Conditional Control Complete */
            conditional_control_complete: boolean;
            /** Decision Acceptable */
            decision_acceptable: boolean;
            /** Decision Action Complete */
            decision_action_complete: boolean;
            /**
             * Decision Action Type Complete
             * @default true
             */
            decision_action_type_complete: boolean;
            /**
             * Development History Reconstructable
             * @default true
             */
            development_history_reconstructable: boolean;
            /**
             * Historical Packet Boundary Preserved
             * @default true
             */
            historical_packet_boundary_preserved: boolean;
            /** Mandatory Claims Covered */
            mandatory_claims_covered: boolean;
            /** Mandatory Dependencies Covered */
            mandatory_dependencies_covered: boolean;
            /** Mandatory Guardrails Covered */
            mandatory_guardrails_covered: boolean;
            /** Passed */
            passed: boolean;
            /** Required Roles Contributed */
            required_roles_contributed: boolean;
            /** Role Differentiation */
            role_differentiation: boolean;
            /** Unresolved Uncertainty Visible */
            unresolved_uncertainty_visible: boolean;
        };
        /**
         * ProjectAttention
         * @enum {string}
         */
        ProjectAttention: "ON_TRACK" | "WATCH" | "AT_RISK" | "BLOCKED";
        /** ProjectAttentionReason */
        ProjectAttentionReason: {
            /**
             * Code
             * @enum {string}
             */
            code: "WORK_ITEM_BLOCKED" | "CRITICAL_RISK" | "HIGH_RISK" | "MILESTONE_AT_RISK" | "EVIDENCE_LATE" | "ACTIVE_RISK" | "NO_ACTIVE_ALERT";
            /** Source Refs */
            source_refs: string[];
            /** Summary Ko */
            summary_ko: string;
        };
        /** ProjectDecisionReferenceProjection */
        ProjectDecisionReferenceProjection: {
            /** Case Id */
            case_id: string;
            /** Href */
            href: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Treated Risk Ids */
            treated_risk_ids: string[];
        };
        /** ProjectEvidenceSituation */
        ProjectEvidenceSituation: {
            /** Available At Step */
            available_at_step: number | null;
            /** Evidence Id */
            evidence_id: string;
            /** Evidence Type */
            evidence_type: string;
            /** Expected At Step */
            expected_at_step: number;
            /** Limitations */
            limitations: string[];
            /** Source Ref */
            source_ref: string | null;
            status: components["schemas"]["EvidenceStatus"];
            /** Title */
            title: string;
        };
        /** ProjectIssueSituation */
        ProjectIssueSituation: {
            /** Affected Milestone Ids */
            affected_milestone_ids: string[];
            /** Affected Work Item Ids */
            affected_work_item_ids: string[];
            /** Issue Id */
            issue_id: string;
            /** Observed At Step */
            observed_at_step: number;
            /** Source Refs */
            source_refs: string[];
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** ProjectListItemProjection */
        ProjectListItemProjection: {
            /** Active Issue Count */
            active_issue_count: number;
            /** Active Risk Count */
            active_risk_count: number;
            /** Aggregate Version */
            aggregate_version: number;
            attention: components["schemas"]["ProjectAttention"];
            /**
             * Attention Policy Version
             * @default project-attention.v1
             * @constant
             */
            attention_policy_version: "project-attention.v1";
            /** Attention Reasons */
            attention_reasons: components["schemas"]["ProjectAttentionReason"][];
            /** Blocked Work Item Count */
            blocked_work_item_count: number;
            /** Current Step */
            current_step: number;
            /** Lifecycle Stage */
            lifecycle_stage: string;
            /** Nearest Milestone Id */
            nearest_milestone_id: string;
            /** Nearest Milestone Step */
            nearest_milestone_step: number;
            /** Project Id */
            project_id: string;
            /**
             * Projection Schema Version
             * @default project-list-item.v1
             * @constant
             */
            projection_schema_version: "project-list-item.v1";
            /** Title Ko */
            title_ko: string;
            /** Top Risks */
            top_risks: components["schemas"]["ProjectRiskSummary"][];
        };
        /** ProjectMilestoneSituation */
        ProjectMilestoneSituation: {
            /** Commitment At Step */
            commitment_at_step: number | null;
            /** Kind */
            kind: string;
            /** Milestone Id */
            milestone_id: string;
            /** Planned At Step */
            planned_at_step: number;
            /** Remaining Steps */
            remaining_steps: number;
            status: components["schemas"]["MilestoneStatus"];
            /** Title */
            title: string;
        };
        /** ProjectRiskDetailProjection */
        ProjectRiskDetailProjection: {
            /** Affected Objects */
            affected_objects: components["schemas"]["RiskAffectedObjectProjection"][];
            /** Blast Radius */
            blast_radius: string;
            /** Cross Project Sources */
            cross_project_sources: components["schemas"]["RiskCrossProjectSourceProjection"][];
            /** Decisions */
            decisions: components["schemas"]["ProjectDecisionReferenceProjection"][];
            /** Downside */
            downside: string;
            /** Epistemic Status */
            epistemic_status: string;
            /** Inference Basis */
            inference_basis: string[];
            /** Project Id */
            project_id: string;
            /**
             * Projection Schema Version
             * @default project-risk-detail.v1
             * @constant
             */
            projection_schema_version: "project-risk-detail.v1";
            /** Reconstructed At Step */
            reconstructed_at_step: number;
            /** Reversibility */
            reversibility: string;
            risk: components["schemas"]["ProjectRiskSummary"];
            /** Source Events */
            source_events: components["schemas"]["RiskSourceEventProjection"][];
            /** Source Evidence */
            source_evidence: components["schemas"]["ProjectEvidenceSituation"][];
            /** Source Issues */
            source_issues: components["schemas"]["RiskSourceIssueProjection"][];
            /** Treatment Actions */
            treatment_actions: components["schemas"]["RiskTreatmentActionProjection"][];
            /** Urgency */
            urgency: string;
        };
        /** ProjectRiskSummary */
        ProjectRiskSummary: {
            /** Affected Milestone Ids */
            affected_milestone_ids: string[];
            /** Affected Work Item Ids */
            affected_work_item_ids: string[];
            /** Missing Evidence Ids */
            missing_evidence_ids: string[];
            /**
             * Policy Version
             * @default project-risk-order.v1
             * @constant
             */
            policy_version: "project-risk-order.v1";
            /** Project Id */
            project_id: string;
            /**
             * Projection Schema Version
             * @default project-risk-summary.v1
             * @constant
             */
            projection_schema_version: "project-risk-summary.v1";
            /** Rank */
            rank: number;
            /** Ranking Reasons */
            ranking_reasons: string[];
            /** Risk Id */
            risk_id: string;
            risk_level: components["schemas"]["RiskLevel"];
            /** Source Refs */
            source_refs: string[];
            /** Statement */
            statement: string;
            status: components["schemas"]["RiskStatus"];
            /** Treatment Action Ids */
            treatment_action_ids: string[];
            /** Treatment Decision Case Ids */
            treatment_decision_case_ids: string[];
        };
        /** ProjectSituationProjection */
        ProjectSituationProjection: {
            /** Aggregate Version */
            aggregate_version: number;
            attention: components["schemas"]["ProjectAttention"];
            /**
             * Attention Policy Version
             * @default project-attention.v1
             * @constant
             */
            attention_policy_version: "project-attention.v1";
            /** Attention Reasons */
            attention_reasons: components["schemas"]["ProjectAttentionReason"][];
            /** Current Step */
            current_step: number;
            /** Decision Case Refs */
            decision_case_refs: components["schemas"]["ProjectDecisionReferenceProjection"][];
            /** Evidence */
            evidence: components["schemas"]["ProjectEvidenceSituation"][];
            /** Fixture Version */
            fixture_version: number;
            /** Issues */
            issues: components["schemas"]["ProjectIssueSituation"][];
            /** Lifecycle Stage */
            lifecycle_stage: string;
            /** Milestones */
            milestones: components["schemas"]["ProjectMilestoneSituation"][];
            /** Project Id */
            project_id: string;
            /**
             * Projection Schema Version
             * @default project-situation.v1
             * @constant
             */
            projection_schema_version: "project-situation.v1";
            /** Reconstructed At Step */
            reconstructed_at_step: number;
            /** Risks */
            risks: components["schemas"]["ProjectRiskSummary"][];
            /** Title Ko */
            title_ko: string;
            /** Tracks */
            tracks: components["schemas"]["ProjectTrackSituation"][];
            /** Work Items */
            work_items: components["schemas"]["ProjectWorkItemSituation"][];
        };
        /** ProjectTimelineEventProjection */
        ProjectTimelineEventProjection: {
            /** Affected Entity Ids */
            affected_entity_ids: string[];
            /** Cause */
            cause: string;
            /** Effective At Step */
            effective_at_step: number;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Impacted Milestone Ids */
            impacted_milestone_ids: string[];
            /** Observed At Step */
            observed_at_step: number;
            /** Summary */
            summary: string;
        };
        /** ProjectTimelineProjection */
        ProjectTimelineProjection: {
            /** Aggregate Version */
            aggregate_version: number;
            attention: components["schemas"]["ProjectAttention"];
            /** Current Step */
            current_step: number;
            /** Events */
            events: components["schemas"]["ProjectTimelineEventProjection"][];
            /** Project Id */
            project_id: string;
            /**
             * Projection Schema Version
             * @default project-timeline.v1
             * @constant
             */
            projection_schema_version: "project-timeline.v1";
            /** Reconstructed At Step */
            reconstructed_at_step: number;
        };
        /** ProjectTrackSituation */
        ProjectTrackSituation: {
            /** Blocked Work Item Count */
            blocked_work_item_count: number;
            /** Name */
            name: string;
            /** Next Milestone Id */
            next_milestone_id: string | null;
            /** Status */
            status: string;
            /** Track Id */
            track_id: string;
        };
        /** ProjectWorkItemSituation */
        ProjectWorkItemSituation: {
            /** Blocker */
            blocker: string | null;
            /** Dependency Ids */
            dependency_ids: string[];
            /** Planned At Step */
            planned_at_step: number;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Track Id */
            track_id: string;
            /** Work Item Id */
            work_item_id: string;
        };
        /** ProviderReviewResult */
        ProviderReviewResult: {
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Returned Model */
            returned_model?: string | null;
            review: components["schemas"]["RoleReview"];
            /**
             * @default {
             *       "estimated_cost_usd": 0,
             *       "input_tokens": 0,
             *       "output_tokens": 0,
             *       "provider_attempts": 1
             *     }
             */
            usage: components["schemas"]["ProviderUsage"];
        };
        /** ProviderUsage */
        ProviderUsage: {
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Provider Attempts
             * @default 1
             */
            provider_attempts: number;
        };
        /** Quantity */
        Quantity: {
            /** Lower Bound */
            lower_bound?: number | null;
            mode: components["schemas"]["QuantityMode"];
            /** Qualitative */
            qualitative?: ("low" | "medium" | "high" | "critical") | null;
            /**
             * Unit
             * @enum {string}
             */
            unit: "mW" | "mJ" | "GB/s" | "Mbps" | "ms" | "fps" | "degC" | "mm2" | "ratio" | "count" | "person_day" | "step";
            /** Upper Bound */
            upper_bound?: number | null;
            /** Value */
            value?: number | null;
        };
        /**
         * QuantityMode
         * @enum {string}
         */
        QuantityMode: "exact" | "range" | "qualitative" | "unknown";
        /** ReviewRunRequest */
        ReviewRunRequest: {
            /**
             * Command Schema Version
             * @default review-run-command.v1
             */
            command_schema_version: string;
            /** Role Id */
            role_id?: string | null;
            /**
             * Scope
             * @default dossier
             * @enum {string}
             */
            scope: "role_review" | "dossier";
        };
        /** ReviewRunView */
        ReviewRunView: {
            /** Actor Id */
            actor_id: string;
            /** Attempt No */
            attempt_no: number;
            budget_plan: components["schemas"]["AgentRunBudgetPlan"];
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Cancel Requested At */
            cancel_requested_at?: string | null;
            /** Case Id */
            case_id: string;
            /** Contract Version */
            contract_version: string;
            /** Created At */
            created_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Events Url */
            events_url: string;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /** Lease Expires At */
            lease_expires_at?: string | null;
            /** Lease Owner */
            lease_owner?: string | null;
            /** Max Attempts */
            max_attempts: number;
            /** Next Retry At */
            next_retry_at?: string | null;
            /** Packet Hash */
            packet_hash: string;
            /** Policy Version */
            policy_version: string;
            /** Prompt Bundle Hash */
            prompt_bundle_hash: string;
            /** Prompt Bundle Version */
            prompt_bundle_version: string;
            /** Provider */
            provider: string;
            /** Requested Model */
            requested_model: string;
            /** Result */
            result?: components["schemas"]["ProviderReviewResult"] | components["schemas"]["DossierExecution"] | null;
            /** Returned Model */
            returned_model: string | null;
            /** Role Id */
            role_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Run Kind
             * @enum {string}
             */
            run_kind: "role_review" | "dossier";
            status: components["schemas"]["AgentRunStatus"];
            /** Status Url */
            status_url: string;
            /** Topology */
            topology: ("B1" | "B2" | "B3") | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** RiskAffectedObjectProjection */
        RiskAffectedObjectProjection: {
            /** Object Id */
            object_id: string;
            /**
             * Object Type
             * @enum {string}
             */
            object_type: "WORK_ITEM" | "MILESTONE";
            /** State */
            state: string;
            /** Title */
            title: string;
        };
        /** RiskAssessment */
        RiskAssessment: {
            /** Claim Ids */
            claim_ids?: string[];
            /** Mitigation */
            mitigation: string;
            /** Risk Id */
            risk_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high" | "critical";
            /** Statement */
            statement: string;
        };
        /** RiskCrossProjectSourceProjection */
        RiskCrossProjectSourceProjection: {
            /** Available At Step */
            available_at_step: number;
            /** Lesson */
            lesson: string;
            /** Source Event Id */
            source_event_id: string;
            /** Source Id */
            source_id: string;
            /** Source Project Id */
            source_project_id: string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** RiskSourceEventProjection */
        RiskSourceEventProjection: {
            /** Event Id */
            event_id: string;
            /** Observed At Step */
            observed_at_step: number;
            /** Summary */
            summary: string;
        };
        /** RiskSourceIssueProjection */
        RiskSourceIssueProjection: {
            /** Issue Id */
            issue_id: string;
            /** Source Refs */
            source_refs: string[];
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /**
         * RiskStatus
         * @enum {string}
         */
        RiskStatus: "OPEN" | "TREATING" | "ACCEPTED" | "REALIZED" | "CLOSED";
        /** RiskTreatmentActionProjection */
        RiskTreatmentActionProjection: {
            /** Action Id */
            action_id: string;
            /** Due At Step */
            due_at_step: number;
            /** Rollback Condition */
            rollback_condition: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Verification Evidence Ids */
            verification_evidence_ids: string[];
        };
        /** RoleFailure */
        RoleFailure: {
            /** Error Code */
            error_code: string;
            /**
             * Provider Attempts
             * @default 1
             */
            provider_attempts: number;
            /** Role Id */
            role_id: string;
        };
        /** RoleReview */
        RoleReview: {
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Information Gaps */
            information_gaps: string[];
            /**
             * No Unique Concern
             * @default false
             */
            no_unique_concern: boolean;
            /** Rationale */
            rationale: string;
            /** Rationale Claim Ids */
            rationale_claim_ids?: string[];
            recommendation: components["schemas"]["DecisionType"];
            /** Recommended Option Id */
            recommended_option_id?: string | null;
            /** Risks */
            risks: components["schemas"]["RiskAssessment"][];
            /** Role Id */
            role_id: string;
            /**
             * Schema Version
             * @default role-review.v1
             * @constant
             */
            schema_version: "role-review.v1";
            /** Unique Concern */
            unique_concern?: string | null;
        };
        /** RunTelemetryView */
        RunTelemetryView: {
            /** Completed Count */
            completed_count: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Provider Attempts */
            provider_attempts: number;
            /** Run Count */
            run_count: number;
        };
        /** Safeguard */
        Safeguard: {
            /** Check At Step */
            check_at_step: number;
            /** Condition */
            condition: string;
            /** Expires At Step */
            expires_at_step: number;
            /** Metric Id */
            metric_id: string;
            /**
             * Operator
             * @enum {string}
             */
            operator: "lt" | "lte" | "gt" | "gte" | "eq";
            /** Owner */
            owner: string;
            /** Rollback Trigger */
            rollback_trigger: string;
            /** Safeguard Id */
            safeguard_id: string;
            threshold: components["schemas"]["Quantity"];
            /** Verification */
            verification: string;
            /**
             * Violation Action
             * @enum {string}
             */
            violation_action: "rollback" | "pause" | "escalate" | "re_review";
        };
        /** SimulatedDecision */
        SimulatedDecision: {
            action_plan: components["schemas"]["DecisionActionPlan"];
            /** Case Id */
            case_id: string;
            /**
             * Decision Source
             * @default simulated_chair
             * @enum {string}
             */
            decision_source: "deterministic_core" | "simulated_chair";
            decision_type: components["schemas"]["DecisionType"];
            /** Dissent Acknowledged */
            dissent_acknowledged: string[];
            /** Rationale */
            rationale: string;
            /** Safeguards */
            safeguards: components["schemas"]["Safeguard"][];
            /**
             * Schema Version
             * @default simulated-decision.v2
             * @constant
             */
            schema_version: "simulated-decision.v2";
            /** Selected Option Id */
            selected_option_id?: string | null;
            /**
             * Simulated
             * @default true
             * @constant
             */
            simulated: true;
        };
        /** TimelineAction */
        TimelineAction: {
            /** Action Id */
            action_id: string;
            /** Blocker */
            blocker: string | null;
            /** Due At Step */
            due_at_step: number;
            /** Owner */
            owner: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** TimelineEvent */
        TimelineEvent: {
            /** Affected Entity Ids */
            affected_entity_ids: string[];
            /** Cause */
            cause: string;
            /** Effective At Step */
            effective_at_step: number;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Impacted Milestone Ids */
            impacted_milestone_ids: string[];
            /** Observed At Step */
            observed_at_step: number;
            /** Summary */
            summary: string;
        };
        /** TimelineEvidence */
        TimelineEvidence: {
            /** Available At Step */
            available_at_step: number;
            /** Eligible At Step */
            eligible_at_step: boolean;
            /** Evidence Id */
            evidence_id: string;
            /** Title */
            title: string;
        };
        /** TimelineMilestone */
        TimelineMilestone: {
            /** Milestone Id */
            milestone_id: string;
            /** Planned At Step */
            planned_at_step: number;
            /** Title */
            title: string;
        };
        /** TimelineWorkItem */
        TimelineWorkItem: {
            /** Blocker */
            blocker: string | null;
            /** Dependency Ids */
            dependency_ids: string[];
            /** Planned At Step */
            planned_at_step: number;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Track Id */
            track_id: string;
            /** Work Item Id */
            work_item_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkItemStatus
         * @enum {string}
         */
        WorkItemStatus: "PLANNED" | "READY" | "IN_PROGRESS" | "BLOCKED" | "DONE" | "VERIFIED" | "REWORK" | "CANCELLED";
        /** WorkspaceActionPlanSummary */
        WorkspaceActionPlanSummary: {
            /** Action Ko */
            action_ko: string;
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "execute" | "collect_evidence" | "defer" | "escalate" | "reject";
            /** Decision Rationale Ko */
            decision_rationale_ko: string;
            /** Decision Type Ko */
            decision_type_ko: string;
            /** Due At Step */
            due_at_step: number;
            /** Escalation Target Ko */
            escalation_target_ko?: string | null;
            /** Evidence Required Ko */
            evidence_required_ko?: string[];
            /** Fallback Action Ko */
            fallback_action_ko: string;
            /** Owner */
            owner: string;
            /** Questions To Resolve Ko */
            questions_to_resolve_ko?: string[];
            /** Reopen Condition Ko */
            reopen_condition_ko?: string | null;
            /** Selected Option Title */
            selected_option_title?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "completed" | "blocked" | "cancelled";
            /** Status Ko */
            status_ko: string;
            /** Trigger Ko */
            trigger_ko: string;
            /** Verification Ko */
            verification_ko: string;
        };
        /** WorkspaceAlignmentGroup */
        WorkspaceAlignmentGroup: {
            /** Recommendation */
            recommendation: string;
            /** Recommendation Ko */
            recommendation_ko: string;
            /** Role Labels Ko */
            role_labels_ko: string[];
            /** Summary Ko */
            summary_ko: string;
        };
        /** WorkspaceAlternativeV2 */
        WorkspaceAlternativeV2: {
            /** Description */
            description: string;
            /** Expected Effect Ko */
            expected_effect_ko?: string | null;
            /** Failure Impact Ko */
            failure_impact_ko?: string[];
            /** Option Id */
            option_id: string;
            /** Recommendation Reason Ko */
            recommendation_reason_ko?: string | null;
            /**
             * Recommended
             * @default false
             */
            recommended: boolean;
            /** Required Evidence Ko */
            required_evidence_ko?: string[];
            /** Residual Risks Ko */
            residual_risks_ko?: string[];
            /** Reversibility Ko */
            reversibility_ko?: string | null;
            /** Reversible */
            reversible: boolean;
            /** Safety Conditions Ko */
            safety_conditions_ko?: string[];
            /** Schedule Impact Ko */
            schedule_impact_ko?: string[];
            switching_cost: components["schemas"]["Quantity"];
            /** Title */
            title: string;
        };
        /** WorkspaceAlternativesV2 */
        WorkspaceAlternativesV2: {
            /** Comparison Dimensions Ko */
            comparison_dimensions_ko: string[];
            /** Items */
            items: components["schemas"]["WorkspaceAlternativeV2"][];
        };
        /** WorkspaceBlockerImpact */
        WorkspaceBlockerImpact: {
            /** Blocker Ko */
            blocker_ko: string;
            /** Downstream Work Item Titles */
            downstream_work_item_titles?: string[];
            /** Impacted Milestone Titles */
            impacted_milestone_titles?: string[];
            /** Reaches Decision Deadline */
            reaches_decision_deadline: boolean;
            /** Source Work Item Title */
            source_work_item_title: string;
        };
        /** WorkspaceCausalChain */
        WorkspaceCausalChain: {
            /** Impacted Milestone Ids */
            impacted_milestone_ids?: string[];
            /** Links */
            links: components["schemas"]["WorkspaceCausalLink"][];
            /** Observed At Step */
            observed_at_step: number;
            /** Source Event Id */
            source_event_id: string;
            /** Title Ko */
            title_ko: string;
        };
        /** WorkspaceCausalLink */
        WorkspaceCausalLink: {
            /** Inference Basis */
            inference_basis?: string[];
            /**
             * Relation Kind
             * @enum {string}
             */
            relation_kind: "observed" | "inferred";
            /** Source Refs */
            source_refs: string[];
            /** Statement Ko */
            statement_ko: string;
        };
        /** WorkspaceChallengeChange */
        WorkspaceChallengeChange: {
            /** After Recommendation Ko */
            after_recommendation_ko: string;
            /** Before Recommendation Ko */
            before_recommendation_ko: string;
            /** Role Label Ko */
            role_label_ko: string;
            /** Summary Ko */
            summary_ko: string;
        };
        /** WorkspaceCommitmentWindow */
        WorkspaceCommitmentWindow: {
            /** Closes At Milestone Id */
            closes_at_milestone_id?: string | null;
            /** Closes At Step */
            closes_at_step?: number | null;
            /** Closing Reason Ko */
            closing_reason_ko: string;
            /** Owner */
            owner: string;
            /** Post Window Impact Ko */
            post_window_impact_ko: string;
            /** Subject Id */
            subject_id: string;
            /** Subject Title */
            subject_title: string;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "work_item" | "milestone" | "alternative" | "interface" | "verification_plan";
            switching_cost?: components["schemas"]["Quantity"] | null;
        };
        /** WorkspaceControls */
        WorkspaceControls: {
            action_plan?: components["schemas"]["WorkspaceActionPlanSummary"] | null;
            /** Safeguards */
            safeguards: components["schemas"]["WorkspaceSafeguardSummary"][];
        };
        /** WorkspaceCurrentBrief */
        WorkspaceCurrentBrief: {
            /** Key Conditions Ko */
            key_conditions_ko?: string[];
            /** One Line Reason Ko */
            one_line_reason_ko: string;
            /** Residual Risks Ko */
            residual_risks_ko?: string[];
            /** State Or Recommendation Ko */
            state_or_recommendation_ko: string;
            /** Why Now Ko */
            why_now_ko: string;
        };
        /** WorkspaceDeadline */
        WorkspaceDeadline: {
            /** At Step */
            at_step: number;
            /** Milestone Id */
            milestone_id: string;
            /** Remaining Steps */
            remaining_steps: number;
            /** Title */
            title: string;
        };
        /** WorkspaceDecisionPosture */
        WorkspaceDecisionPosture: {
            /**
             * Blast Radius
             * @enum {string}
             */
            blast_radius: "limited" | "cross_track" | "milestone" | "project" | "unknown";
            /**
             * Detectability
             * @enum {string}
             */
            detectability: "observable_now" | "observable_later" | "unknown";
            /**
             * Downside
             * @enum {string}
             */
            downside: "low" | "medium" | "high" | "critical" | "unknown";
            /**
             * Evidence State
             * @enum {string}
             */
            evidence_state: "sufficient" | "partial" | "insufficient";
            /** Explanations Ko */
            explanations_ko: string[];
            /**
             * Recoverability
             * @enum {string}
             */
            recoverability: "high" | "medium" | "low";
            /**
             * Reversibility
             * @enum {string}
             */
            reversibility: "high" | "medium" | "low";
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "low" | "medium" | "high" | "expired";
        };
        /** WorkspaceDeliberation */
        WorkspaceDeliberation: {
            /** Agreement Groups */
            agreement_groups?: components["schemas"]["WorkspaceAlignmentGroup"][];
            /** Agreement Ko */
            agreement_ko: string[];
            /**
             * Alignment Available
             * @default false
             */
            alignment_available: boolean;
            /** Challenge Changes */
            challenge_changes?: components["schemas"]["WorkspaceChallengeChange"][];
            /** Changed After Challenge Ko */
            changed_after_challenge_ko: string[];
            /** Dissent Items */
            dissent_items?: components["schemas"]["WorkspaceDissentSummary"][];
            /** Dissent Ko */
            dissent_ko: string[];
            /** Epistemic Items */
            epistemic_items?: components["schemas"]["WorkspaceEpistemicItem"][];
            /** Key Assumptions Ko */
            key_assumptions_ko: string[];
            /** Key Unknowns Ko */
            key_unknowns_ko: string[];
            /** Needs Confirmation Ko */
            needs_confirmation_ko: string[];
            /** Role Reviews */
            role_reviews?: components["schemas"]["WorkspaceRoleReviewDetail"][];
        };
        /** WorkspaceDetails */
        WorkspaceDetails: {
            /** Evidence Available */
            evidence_available: boolean;
            /** Impact Path Available */
            impact_path_available: boolean;
            /** Role Originals Available */
            role_originals_available: boolean;
            /** Timeline Available */
            timeline_available: boolean;
        };
        /** WorkspaceDevelopmentTwin */
        WorkspaceDevelopmentTwin: {
            /** Blocker Impacts */
            blocker_impacts?: components["schemas"]["WorkspaceBlockerImpact"][];
            /** Causal Chains */
            causal_chains: components["schemas"]["WorkspaceCausalChain"][];
            /** Commitment Windows */
            commitment_windows: components["schemas"]["WorkspaceCommitmentWindow"][];
            /** Delay Summary Ko */
            delay_summary_ko: string;
            /** Recent Decision Relevant Event Ids */
            recent_decision_relevant_event_ids: string[];
            state_at_selected_step: components["schemas"]["WorkspaceStateAtStep"];
        };
        /** WorkspaceDissentSummary */
        WorkspaceDissentSummary: {
            /** Rationale Ko */
            rationale_ko: string;
            /** Recommendation */
            recommendation: string;
            /** Recommendation Ko */
            recommendation_ko: string;
            /** Role Label Ko */
            role_label_ko: string;
        };
        /** WorkspaceEpistemicItem */
        WorkspaceEpistemicItem: {
            /**
             * Epistemic Status
             * @enum {string}
             */
            epistemic_status: "fact" | "inference" | "assumption" | "unknown";
            /** Expected Confirmation Step */
            expected_confirmation_step?: number | null;
            /** Expires At Step */
            expires_at_step?: number | null;
            /** Inference Basis Ko */
            inference_basis_ko?: string[];
            /** Observed At Step */
            observed_at_step?: number | null;
            /** Owner Ko */
            owner_ko?: string | null;
            /** Source Titles Ko */
            source_titles_ko?: string[];
            /** Statement Ko */
            statement_ko: string;
            /** Unknown Reason Ko */
            unknown_reason_ko?: string | null;
        };
        /** WorkspaceExpectedOptionTransition */
        WorkspaceExpectedOptionTransition: {
            /**
             * Label
             * @default expected_from_observable_model
             * @constant
             */
            label: "expected_from_observable_model";
            /** Lost Options Ko */
            lost_options_ko?: string[];
            /** Model Basis */
            model_basis?: string[];
            /** Option Id */
            option_id: string;
            /** Option Title */
            option_title: string;
            /** Preserved Options Ko */
            preserved_options_ko?: string[];
            /** State Changes */
            state_changes: components["schemas"]["WorkspaceStateTransition"][];
            /** Unknown Impacts Ko */
            unknown_impacts_ko?: string[];
        };
        /** WorkspaceHeaderV2 */
        WorkspaceHeaderV2: {
            case_status?: components["schemas"]["DecisionCaseStatus"] | null;
            deadline: components["schemas"]["WorkspaceDeadline"];
            /** Decision Question */
            decision_question: string;
            /**
             * Simulated
             * @default true
             * @constant
             */
            simulated: true;
            /** Title Ko */
            title_ko: string;
            workspace_phase?: components["schemas"]["WorkspacePhase"] | null;
        };
        /** WorkspaceObservedDecisionTransitions */
        WorkspaceObservedDecisionTransitions: {
            /** Available */
            available: boolean;
            /** Decision Id */
            decision_id?: string | null;
            /** Guardrail Events Ko */
            guardrail_events_ko?: string[];
            /** State Changes */
            state_changes?: components["schemas"]["WorkspaceStateTransition"][];
        };
        /** WorkspaceOutcomeAndEvaluation */
        WorkspaceOutcomeAndEvaluation: {
            /** Actual Ko */
            actual_ko?: string[];
            /** Expectation Vs Actual Ko */
            expectation_vs_actual_ko?: string[];
            /** Expected Ko */
            expected_ko?: string[];
            /** Guardrail Results Ko */
            guardrail_results_ko?: string[];
            /** Hidden Until Step Advance */
            hidden_until_step_advance: boolean;
            /** Lessons Ko */
            lessons_ko?: string[];
            /** Outcome Evaluation Ko */
            outcome_evaluation_ko?: string | null;
            /**
             * Outcome State
             * @enum {string}
             */
            outcome_state: "not_available" | "running" | "available";
            /** Process Evaluation Ko */
            process_evaluation_ko?: string | null;
        };
        /**
         * WorkspacePhase
         * @enum {string}
         */
        WorkspacePhase: "CONTEXT_PREPARATION" | "READY_FOR_REVIEW" | "REVIEW_RUNNING" | "DOSSIER_READY" | "DECISION_REQUIRED" | "OUTCOME_RUNNING" | "EVALUATION_READY" | "CLOSED";
        /** WorkspaceRoleReviewDetail */
        WorkspaceRoleReviewDetail: {
            /** Confidence Ko */
            confidence_ko: string;
            /** Information Gaps Ko */
            information_gaps_ko?: string[];
            /** Rationale Ko */
            rationale_ko: string;
            /** Recommendation Ko */
            recommendation_ko: string;
            /** Recommended Option Title */
            recommended_option_title?: string | null;
            revision?: components["schemas"]["WorkspaceRoleRevision"] | null;
            /** Risks Ko */
            risks_ko?: string[];
            /** Role Label Ko */
            role_label_ko: string;
            /** Unique Concern Ko */
            unique_concern_ko?: string | null;
        };
        /** WorkspaceRoleRevision */
        WorkspaceRoleRevision: {
            /** Rationale Ko */
            rationale_ko: string;
            /** Recommendation Ko */
            recommendation_ko: string;
        };
        /** WorkspaceSafeguardSummary */
        WorkspaceSafeguardSummary: {
            /** Cause Ko */
            cause_ko: string;
            /** Check At Step */
            check_at_step: number;
            /** Condition Ko */
            condition_ko: string;
            /** Expires At Step */
            expires_at_step: number;
            /** Metric Id */
            metric_id: string;
            /** Metric Label Ko */
            metric_label_ko: string;
            /**
             * Operator
             * @enum {string}
             */
            operator: "lt" | "lte" | "gt" | "gte" | "eq";
            /** Operator Ko */
            operator_ko: string;
            /** Owner */
            owner: string;
            /** Rollback Trigger Ko */
            rollback_trigger_ko: string;
            /** Safeguard Id */
            safeguard_id: string;
            /** Threshold Ko */
            threshold_ko: string;
            /** Verification Ko */
            verification_ko: string;
            /** Violation Action Ko */
            violation_action_ko: string;
        };
        /** WorkspaceStateAtStep */
        WorkspaceStateAtStep: {
            /** Active Action Ids */
            active_action_ids: string[];
            /** Eligible Evidence Ids */
            eligible_evidence_ids: string[];
            /** Reconstructed At Step */
            reconstructed_at_step: number;
            /** Tracks */
            tracks: components["schemas"]["WorkspaceTrackState"][];
            /** Unavailable Evidence Ids */
            unavailable_evidence_ids: string[];
        };
        /** WorkspaceStateTransition */
        WorkspaceStateTransition: {
            /** Basis Refs */
            basis_refs: string[];
            /** Entity Id */
            entity_id: string;
            /** Entity Title */
            entity_title: string;
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "action" | "work_item" | "milestone" | "evidence";
            /** From State */
            from_state: string;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "expected_model" | "observed_event";
            /** To State */
            to_state: string;
        };
        /** WorkspaceTimeContext */
        WorkspaceTimeContext: {
            /** Commands Allowed At Selected Step */
            commands_allowed_at_selected_step: boolean;
            /** Current Step */
            current_step: number;
            /** Earliest Available Step */
            earliest_available_step: number;
            /** Latest Observable Step */
            latest_observable_step: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "current" | "historical";
            /** Next Expected Evidence Step */
            next_expected_evidence_step?: number | null;
            /** Selected Step */
            selected_step: number;
        };
        /** WorkspaceTrackState */
        WorkspaceTrackState: {
            /** Blocker */
            blocker?: string | null;
            /** Current Work Item Id */
            current_work_item_id: string;
            /** Current Work Item Title */
            current_work_item_title: string;
            /** Name */
            name: string;
            /** Next Milestone Id */
            next_milestone_id?: string | null;
            /** Next Milestone Step */
            next_milestone_step?: number | null;
            /** Next Milestone Title */
            next_milestone_title?: string | null;
            /** Owner */
            owner: string;
            status: components["schemas"]["WorkItemStatus"];
            /** Track Id */
            track_id: string;
        };
        /** WorkspaceWorkflow */
        WorkspaceWorkflow: {
            /** Allowed Actions */
            allowed_actions: ("BUILD_CONTEXT" | "RUN_VIRTUAL_REVIEW" | "VIEW_REVIEW_PROGRESS" | "VIEW_DOSSIER" | "RUN_SIMULATED_DECISION" | "ADVANCE_SIMULATION" | "VIEW_EVALUATION" | "VIEW_LEARNING_SUMMARY" | "REFRESH_STALE")[];
            /** Dossier Run Id */
            dossier_run_id?: string | null;
            /** Primary Action */
            primary_action?: ("BUILD_CONTEXT" | "RUN_VIRTUAL_REVIEW" | "VIEW_REVIEW_PROGRESS" | "VIEW_DOSSIER" | "RUN_SIMULATED_DECISION" | "ADVANCE_SIMULATION" | "VIEW_EVALUATION" | "VIEW_LEARNING_SUMMARY" | "REFRESH_STALE") | null;
            /** Running Operation Ko */
            running_operation_ko?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cases_api_v1_decision_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionListItemProjection"][];
                };
            };
        };
    };
    get_evaluation_api_v1_decision_cases__case_id__evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseEvaluation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_api_v1_decision_cases__case_id__evaluations_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseEvaluation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_decision_cases__case_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_outcome_advance_api_v1_decision_cases__case_id__outcome_advances_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeAdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_run_api_v1_decision_cases__case_id__review_runs_post: {
        parameters: {
            query?: {
                role_id?: string | null;
            };
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewRunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_simulated_decision_api_v1_decision_cases__case_id__simulated_decisions_post: {
        parameters: {
            query: {
                review_run_id: string;
            };
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AblationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_api_v1_decision_cases__case_id__timeline_get: {
        parameters: {
            query?: {
                at_step?: number | null;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevelopmentTimelineProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_decision_cases__case_id__workspace_get: {
        parameters: {
            query?: {
                at_step?: number | null;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionWorkspaceProjectionV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_observable_packet_api_v1_dev_fixtures__case_id__observable_get: {
        parameters: {
            query?: {
                at_step?: number | null;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListItemProjection"][];
                };
            };
        };
    };
    get_project_risks_api_v1_projects__project_id__risks_get: {
        parameters: {
            query?: {
                at_step?: number | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRiskSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_risk_detail_api_v1_projects__project_id__risks__risk_id__get: {
        parameters: {
            query?: {
                at_step?: number | null;
            };
            header?: never;
            path: {
                project_id: string;
                risk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRiskDetailProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_situation_api_v1_projects__project_id__situation_get: {
        parameters: {
            query?: {
                at_step?: number | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSituationProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_timeline_api_v1_projects__project_id__timeline_get: {
        parameters: {
            query?: {
                at_step?: number | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectTimelineProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                follow?: boolean;
            };
            header?: {
                "Last-Event-ID"?: number | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_api_v1_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_run_telemetry_api_v1_telemetry_agent_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTelemetryView"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
