/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/decision-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_v1_decision_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_api_v1_decision_cases__case_id__evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evaluation */
        post: operations["create_evaluation_api_v1_decision_cases__case_id__evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_decision_cases__case_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/outcome-advances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Outcome Advance */
        post: operations["create_outcome_advance_api_v1_decision_cases__case_id__outcome_advances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/review-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Review Run */
        post: operations["create_review_run_api_v1_decision_cases__case_id__review_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/simulated-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Simulated Decision */
        post: operations["create_simulated_decision_api_v1_decision_cases__case_id__simulated_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_v1_decision_cases__case_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-cases/{case_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_decision_cases__case_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/fixtures/{case_id}/observable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Observable Packet */
        get: operations["get_observable_packet_api_v1_dev_fixtures__case_id__observable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["stream_run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Run */
        post: operations["retry_run_api_v1_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Run Telemetry */
        get: operations["agent_run_telemetry_api_v1_telemetry_agent_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AblationResult */
        AblationResult: {
            /** Chair Used */
            chair_used: boolean;
            /** Challenger Used */
            challenger_used: boolean;
            decision: components["schemas"]["SimulatedDecision"];
            dossier: components["schemas"]["DecisionDossier"];
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Provider Attempts
             * @default 0
             */
            provider_attempts: number;
            /** Role Count */
            role_count: number;
            /**
             * Topology
             * @enum {string}
             */
            topology: "B0" | "B1" | "B2" | "B3";
        };
        /** AgentRunBudgetPlan */
        AgentRunBudgetPlan: {
            /**
             * Max Logical Calls
             * @default 9
             */
            max_logical_calls: number;
            /**
             * Max Output Tokens
             * @default 20000
             */
            max_output_tokens: number;
            /**
             * Max Provider Attempts
             * @default 12
             */
            max_provider_attempts: number;
            /** Maximum Cost Usd */
            maximum_cost_usd: number;
            /** Remaining Logical Calls */
            remaining_logical_calls: number;
            /** Remaining Output Tokens */
            remaining_output_tokens: number;
            /** Remaining Provider Attempts */
            remaining_provider_attempts: number;
            /** Reserved Logical Calls */
            reserved_logical_calls: number;
            /** Reserved Output Tokens */
            reserved_output_tokens: number;
            /** Reserved Provider Attempts */
            reserved_provider_attempts: number;
            /** Timeout Envelope Seconds */
            timeout_envelope_seconds: number;
        };
        /**
         * AgentRunStatus
         * @enum {string}
         */
        AgentRunStatus: "QUEUED" | "RUNNING" | "PARTIALLY_COMPLETED" | "COMPLETED" | "FAILED" | "CANCELLED";
        /** AgreementGroup */
        AgreementGroup: {
            recommendation: components["schemas"]["DecisionType"];
            /** Role Ids */
            role_ids: string[];
        };
        /** AlternativeSummary */
        AlternativeSummary: {
            /** Description */
            description: string;
            /** Option Id */
            option_id: string;
            /** Reversible */
            reversible: boolean;
            /** Title */
            title: string;
        };
        /** BlockerSummary */
        BlockerSummary: {
            /** Blocker */
            blocker: string;
            /** Dependency Ids */
            dependency_ids: string[];
            /** Track Id */
            track_id: string;
            /** Work Item Title */
            work_item_title: string;
        };
        /** CaseEvaluation */
        CaseEvaluation: {
            ablation: components["schemas"]["AblationResult"];
            /** Case Id */
            case_id: string;
            outcome: components["schemas"]["OutcomeSnapshot"];
            outcome_evaluation: components["schemas"]["OutcomeEvaluation"];
            /** Partition */
            partition: string;
            /** Passed */
            passed: boolean;
            process_evaluation: components["schemas"]["ProcessEvaluation"];
            /**
             * Schema Version
             * @default case-evaluation.v1
             * @constant
             */
            schema_version: "case-evaluation.v1";
            /**
             * Topology
             * @enum {string}
             */
            topology: "B0" | "B1" | "B2" | "B3";
        };
        /** ChairProviderResult */
        ChairProviderResult: {
            decision: components["schemas"]["SimulatedDecision"];
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Returned Model */
            returned_model?: string | null;
            /**
             * @default {
             *       "estimated_cost_usd": 0,
             *       "input_tokens": 0,
             *       "output_tokens": 0,
             *       "provider_attempts": 1
             *     }
             */
            usage: components["schemas"]["ProviderUsage"];
        };
        /** ChallengerObjection */
        ChallengerObjection: {
            /** Claim Ids */
            claim_ids?: string[];
            /** Objection Id */
            objection_id: string;
            /** Requested Revision */
            requested_revision: string;
            /** Statement */
            statement: string;
            /** Target Role Id */
            target_role_id: string;
        };
        /** ChallengerProviderResult */
        ChallengerProviderResult: {
            challenger: components["schemas"]["ChallengerReview"];
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Returned Model */
            returned_model?: string | null;
            /**
             * @default {
             *       "estimated_cost_usd": 0,
             *       "input_tokens": 0,
             *       "output_tokens": 0,
             *       "provider_attempts": 1
             *     }
             */
            usage: components["schemas"]["ProviderUsage"];
        };
        /** ChallengerReview */
        ChallengerReview: {
            /** No Objection Reason */
            no_objection_reason?: string | null;
            /** Objections */
            objections: components["schemas"]["ChallengerObjection"][];
            /**
             * Schema Version
             * @default challenger-review.v1
             * @constant
             */
            schema_version: "challenger-review.v1";
        };
        /** ClaimSummary */
        ClaimSummary: {
            /** Claim Id */
            claim_id: string;
            /** Confidence Level */
            confidence_level: string;
            /** Epistemic Status */
            epistemic_status: string;
            /** Source Refs */
            source_refs: string[];
            /** Statement */
            statement: string;
        };
        /** DecisionActionPlan */
        DecisionActionPlan: {
            /** Action */
            action: string;
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "execute" | "collect_evidence" | "defer" | "escalate" | "reject";
            /** Due At Step */
            due_at_step: number;
            /** Escalation Target */
            escalation_target?: string | null;
            /** Evidence Required */
            evidence_required?: string[];
            /** Fallback Action */
            fallback_action: string;
            /** Owner */
            owner: string;
            /** Questions To Resolve */
            questions_to_resolve?: string[];
            /** Reopen Condition */
            reopen_condition?: string | null;
            /**
             * Schema Version
             * @default decision-action-plan.v1
             * @constant
             */
            schema_version: "decision-action-plan.v1";
            /** Trigger */
            trigger: string;
            /** Verification */
            verification: string;
        };
        /** DecisionDossier */
        DecisionDossier: {
            /** Agreement Groups */
            agreement_groups: components["schemas"]["AgreementGroup"][];
            /** Case Id */
            case_id: string;
            challenger?: components["schemas"]["ChallengerReview"] | null;
            /** Dissent */
            dissent: components["schemas"]["DissentItem"][];
            /** Original Reviews */
            original_reviews: components["schemas"]["RoleReview"][];
            /** Packet Hash */
            packet_hash: string;
            /** Revised Reviews */
            revised_reviews?: components["schemas"]["RoleReview"][];
            /**
             * Schema Version
             * @default decision-dossier.v1
             * @constant
             */
            schema_version: "decision-dossier.v1";
            /** Unresolved Uncertainties */
            unresolved_uncertainties: string[];
        };
        /**
         * DecisionType
         * @enum {string}
         */
        DecisionType: "APPROVE" | "APPROVE_WITH_GUARDRAILS" | "RUN_REVERSIBLE_TRIAL" | "COLLECT_MINIMUM_EVIDENCE" | "DEFER_UNTIL_TRIGGER" | "REJECT" | "ESCALATE";
        /** DecisionWorkspaceProjection */
        DecisionWorkspaceProjection: {
            /** Aggregate Version */
            aggregate_version: number;
            /** Alternative Count */
            alternative_count: number;
            /** Alternatives */
            alternatives: components["schemas"]["AlternativeSummary"][];
            /** Blockers */
            blockers: components["schemas"]["BlockerSummary"][];
            /** Case Id */
            case_id: string;
            /** Case Status */
            case_status: string;
            /** Claims */
            claims: components["schemas"]["ClaimSummary"][];
            /** Current Step */
            current_step: number;
            /** Deadline Milestone Id */
            deadline_milestone_id: string;
            /** Deadline Step */
            deadline_step: number;
            /** Deadline Title */
            deadline_title: string;
            /** Decision Question */
            decision_question: string;
            /** Eligible Evidence Titles */
            eligible_evidence_titles: string[];
            /** Evidence */
            evidence: components["schemas"]["EvidenceSummary"][];
            /** Evidence Count */
            evidence_count: number;
            /** Fixture Version */
            fixture_version: number;
            /**
             * Projection Schema Version
             * @default decision-workspace.v1
             */
            projection_schema_version: string;
            /** Title Ko */
            title_ko: string;
            /** Tracks */
            tracks: components["schemas"]["TrackSummary"][];
            /** Uncertainties */
            uncertainties: string[];
            /** Uncertainty Count */
            uncertainty_count: number;
        };
        /** DissentItem */
        DissentItem: {
            /** Rationale */
            rationale: string;
            recommendation: components["schemas"]["DecisionType"];
            /** Role Id */
            role_id: string;
        };
        /** DossierExecution */
        DossierExecution: {
            /** Accepted Revision Results */
            accepted_revision_results?: components["schemas"]["ProviderReviewResult"][];
            /** Accepted Role Results */
            accepted_role_results?: components["schemas"]["ProviderReviewResult"][];
            chair_provider_result?: components["schemas"]["ChairProviderResult"] | null;
            challenger_provider_result?: components["schemas"]["ChallengerProviderResult"] | null;
            /** Challenger Used */
            challenger_used: boolean;
            dossier: components["schemas"]["DecisionDossier"];
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /** Failed Revisions */
            failed_revisions?: components["schemas"]["RoleFailure"][];
            /** Failed Roles */
            failed_roles?: components["schemas"]["RoleFailure"][];
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Provider Attempts
             * @default 0
             */
            provider_attempts: number;
            /** Returned Models */
            returned_models: string[];
            /** Role Count */
            role_count: number;
            /**
             * Schema Version
             * @default dossier-execution.v1
             * @constant
             */
            schema_version: "dossier-execution.v1";
            /**
             * Topology
             * @enum {string}
             */
            topology: "B1" | "B2" | "B3";
        };
        /** Evidence */
        Evidence: {
            /** Available At Step */
            available_at_step: number;
            /** Evidence Id */
            evidence_id: string;
            /** Evidence Type */
            evidence_type: string;
            /** Limitations */
            limitations?: string[];
            quantity?: components["schemas"]["Quantity"] | null;
            /** Source Ref */
            source_ref: string;
            /** Title */
            title: string;
        };
        /** EvidenceSummary */
        EvidenceSummary: {
            /** Available At Step */
            available_at_step: number;
            /** Eligible Now */
            eligible_now: boolean;
            /** Evidence Id */
            evidence_id: string;
            /** Evidence Type */
            evidence_type: string;
            /** Limitations */
            limitations: string[];
            /** Source Ref */
            source_ref: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OutcomeAdvanceRequest */
        OutcomeAdvanceRequest: {
            /**
             * Command Schema Version
             * @default outcome-advance-command.v1
             */
            command_schema_version: string;
            decision: components["schemas"]["SimulatedDecision"];
            /** From Step */
            from_step: number;
            /** To Step */
            to_step: number;
        };
        /** OutcomeEvaluation */
        OutcomeEvaluation: {
            /** Evidence Revealed */
            evidence_revealed: boolean;
            /** Passed */
            passed: boolean;
            /** Risk Contained */
            risk_contained: boolean;
            /** Rule Executed */
            rule_executed: boolean;
        };
        /** OutcomeSnapshot */
        OutcomeSnapshot: {
            /** Advanced From Step */
            advanced_from_step: number;
            /** Case Id */
            case_id: string;
            /** Consequences */
            consequences: string[];
            /** Current Step */
            current_step: number;
            /** Decision Id */
            decision_id: string;
            /** Event Ids */
            event_ids: string[];
            /** Executed Actions */
            executed_actions: string[];
            /**
             * Guardrail State
             * @enum {string}
             */
            guardrail_state: "not_applicable" | "monitoring" | "triggered";
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Outcome Rule Version */
            outcome_rule_version: string;
            /** Revealed Evidence */
            revealed_evidence: string[];
            /** Rule Id */
            rule_id: string;
            /**
             * Schema Version
             * @default outcome-snapshot.v1
             * @constant
             */
            schema_version: "outcome-snapshot.v1";
            /** Selected Option Id */
            selected_option_id: string;
        };
        /** ProcessEvaluation */
        ProcessEvaluation: {
            /** Conditional Control Complete */
            conditional_control_complete: boolean;
            /** Decision Acceptable */
            decision_acceptable: boolean;
            /** Decision Action Complete */
            decision_action_complete: boolean;
            /** Mandatory Claims Covered */
            mandatory_claims_covered: boolean;
            /** Mandatory Dependencies Covered */
            mandatory_dependencies_covered: boolean;
            /** Mandatory Guardrails Covered */
            mandatory_guardrails_covered: boolean;
            /** Passed */
            passed: boolean;
            /** Required Roles Contributed */
            required_roles_contributed: boolean;
            /** Role Differentiation */
            role_differentiation: boolean;
            /** Unresolved Uncertainty Visible */
            unresolved_uncertainty_visible: boolean;
        };
        /** ProviderReviewResult */
        ProviderReviewResult: {
            /** Provider Request Id */
            provider_request_id?: string | null;
            /** Returned Model */
            returned_model?: string | null;
            review: components["schemas"]["RoleReview"];
            /**
             * @default {
             *       "estimated_cost_usd": 0,
             *       "input_tokens": 0,
             *       "output_tokens": 0,
             *       "provider_attempts": 1
             *     }
             */
            usage: components["schemas"]["ProviderUsage"];
        };
        /** ProviderUsage */
        ProviderUsage: {
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Provider Attempts
             * @default 1
             */
            provider_attempts: number;
        };
        /** Quantity */
        Quantity: {
            /** Lower Bound */
            lower_bound?: number | null;
            mode: components["schemas"]["QuantityMode"];
            /** Qualitative */
            qualitative?: ("low" | "medium" | "high" | "critical") | null;
            /**
             * Unit
             * @enum {string}
             */
            unit: "mW" | "mJ" | "GB/s" | "Mbps" | "ms" | "fps" | "degC" | "mm2" | "ratio" | "count" | "person_day" | "step";
            /** Upper Bound */
            upper_bound?: number | null;
            /** Value */
            value?: number | null;
        };
        /**
         * QuantityMode
         * @enum {string}
         */
        QuantityMode: "exact" | "range" | "qualitative" | "unknown";
        /** ReviewRunRequest */
        ReviewRunRequest: {
            /**
             * Command Schema Version
             * @default review-run-command.v1
             */
            command_schema_version: string;
            /** Role Id */
            role_id?: string | null;
            /**
             * Scope
             * @default dossier
             * @enum {string}
             */
            scope: "role_review" | "dossier";
        };
        /** ReviewRunView */
        ReviewRunView: {
            /** Actor Id */
            actor_id: string;
            /** Attempt No */
            attempt_no: number;
            budget_plan: components["schemas"]["AgentRunBudgetPlan"];
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Cancel Requested At */
            cancel_requested_at?: string | null;
            /** Case Id */
            case_id: string;
            /** Contract Version */
            contract_version: string;
            /** Created At */
            created_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Events Url */
            events_url: string;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /** Lease Expires At */
            lease_expires_at?: string | null;
            /** Lease Owner */
            lease_owner?: string | null;
            /** Max Attempts */
            max_attempts: number;
            /** Next Retry At */
            next_retry_at?: string | null;
            /** Packet Hash */
            packet_hash: string;
            /** Policy Version */
            policy_version: string;
            /** Prompt Bundle Hash */
            prompt_bundle_hash: string;
            /** Prompt Bundle Version */
            prompt_bundle_version: string;
            /** Provider */
            provider: string;
            /** Requested Model */
            requested_model: string;
            /** Result */
            result?: components["schemas"]["ProviderReviewResult"] | components["schemas"]["DossierExecution"] | null;
            /** Returned Model */
            returned_model: string | null;
            /** Role Id */
            role_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Run Kind
             * @enum {string}
             */
            run_kind: "role_review" | "dossier";
            status: components["schemas"]["AgentRunStatus"];
            /** Status Url */
            status_url: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** RiskAssessment */
        RiskAssessment: {
            /** Claim Ids */
            claim_ids?: string[];
            /** Mitigation */
            mitigation: string;
            /** Risk Id */
            risk_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high" | "critical";
            /** Statement */
            statement: string;
        };
        /** RoleFailure */
        RoleFailure: {
            /** Error Code */
            error_code: string;
            /**
             * Provider Attempts
             * @default 1
             */
            provider_attempts: number;
            /** Role Id */
            role_id: string;
        };
        /** RoleReview */
        RoleReview: {
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Information Gaps */
            information_gaps: string[];
            /**
             * No Unique Concern
             * @default false
             */
            no_unique_concern: boolean;
            /** Rationale */
            rationale: string;
            /** Rationale Claim Ids */
            rationale_claim_ids?: string[];
            recommendation: components["schemas"]["DecisionType"];
            /** Recommended Option Id */
            recommended_option_id?: string | null;
            /** Risks */
            risks: components["schemas"]["RiskAssessment"][];
            /** Role Id */
            role_id: string;
            /**
             * Schema Version
             * @default role-review.v1
             * @constant
             */
            schema_version: "role-review.v1";
            /** Unique Concern */
            unique_concern?: string | null;
        };
        /** RunTelemetryView */
        RunTelemetryView: {
            /** Completed Count */
            completed_count: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Provider Attempts */
            provider_attempts: number;
            /** Run Count */
            run_count: number;
        };
        /** Safeguard */
        Safeguard: {
            /** Check At Step */
            check_at_step: number;
            /** Condition */
            condition: string;
            /** Expires At Step */
            expires_at_step: number;
            /** Metric Id */
            metric_id: string;
            /**
             * Operator
             * @enum {string}
             */
            operator: "lt" | "lte" | "gt" | "gte" | "eq";
            /** Owner */
            owner: string;
            /** Rollback Trigger */
            rollback_trigger: string;
            /** Safeguard Id */
            safeguard_id: string;
            threshold: components["schemas"]["Quantity"];
            /** Verification */
            verification: string;
            /**
             * Violation Action
             * @enum {string}
             */
            violation_action: "rollback" | "pause" | "escalate" | "re_review";
        };
        /** SimulatedDecision */
        SimulatedDecision: {
            action_plan: components["schemas"]["DecisionActionPlan"];
            /** Case Id */
            case_id: string;
            /**
             * Decision Source
             * @default simulated_chair
             * @enum {string}
             */
            decision_source: "deterministic_core" | "simulated_chair";
            decision_type: components["schemas"]["DecisionType"];
            /** Dissent Acknowledged */
            dissent_acknowledged: string[];
            /** Rationale */
            rationale: string;
            /** Safeguards */
            safeguards: components["schemas"]["Safeguard"][];
            /**
             * Schema Version
             * @default simulated-decision.v2
             * @constant
             */
            schema_version: "simulated-decision.v2";
            /** Selected Option Id */
            selected_option_id?: string | null;
            /**
             * Simulated
             * @default true
             * @constant
             */
            simulated: true;
        };
        /** TrackSummary */
        TrackSummary: {
            /** Blocker Count */
            blocker_count: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Track Id */
            track_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cases_api_v1_decision_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionWorkspaceProjection"][];
                };
            };
        };
    };
    get_evaluation_api_v1_decision_cases__case_id__evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseEvaluation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_api_v1_decision_cases__case_id__evaluations_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseEvaluation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_decision_cases__case_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_outcome_advance_api_v1_decision_cases__case_id__outcome_advances_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeAdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_run_api_v1_decision_cases__case_id__review_runs_post: {
        parameters: {
            query?: {
                role_id?: string | null;
            };
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewRunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_simulated_decision_api_v1_decision_cases__case_id__simulated_decisions_post: {
        parameters: {
            query: {
                review_run_id: string;
            };
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AblationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_api_v1_decision_cases__case_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_decision_cases__case_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionWorkspaceProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_observable_packet_api_v1_dev_fixtures__case_id__observable_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                follow?: boolean;
            };
            header?: {
                "Last-Event-ID"?: number | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_api_v1_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "If-Match": string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_run_telemetry_api_v1_telemetry_agent_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTelemetryView"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
